# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: chmod +x gradlew
    - run: ./gradlew compileJAVA
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build

  Test:
    needs: [Compile]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: build
    - run: chmod +x gradlew
    - run: ./gradlew test
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build
    - uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports


  Assemble:
    needs: [Test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: build

    - run: chmod +x gradlew
    - run: ./gradlew assemble
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: build/libs/st_nycu_lab4_309552034-1.0-SNAPSHOT.jar

  Release:
    needs: [Assemble]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: build
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/st_nycu_lab4_309552034-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
